<?php

namespace App\Support\Translations;

use DOMDocument;
use DOMElement;
use RuntimeException;

/**
 * Reads the app's res/values*\/*.xml (read-only) and writes generated values-{qualifier} files.
 * Entries: name => string, or name => [quantity => string] for <plurals>.
 */
final class AndroidStringsXml
{
    /** @var list<string> */
    public const QUANTITIES = ['zero', 'one', 'two', 'few', 'many', 'other'];

    /**
     * @return array<string, string|array<string, string>>
     */
    public static function parse(string $xml): array
    {
        $document = new DOMDocument;

        if (! @$document->loadXML($xml, LIBXML_NONET)) {
            throw new RuntimeException('Invalid Android strings XML.');
        }

        if ($document->doctype !== null) {
            throw new RuntimeException('DOCTYPE is not allowed in Android strings XML.');
        }

        $entries = [];

        foreach ($document->documentElement?->childNodes ?? [] as $node) {
            if (! $node instanceof DOMElement || $node->getAttribute('translatable') === 'false') {
                continue;
            }

            $name = $node->getAttribute('name');

            if ($name === '') {
                continue;
            }

            if ($node->tagName === 'string') {
                $entries[$name] = self::decode($node->textContent);
            } elseif ($node->tagName === 'plurals') {
                $forms = [];

                foreach ($node->getElementsByTagName('item') as $item) {
                    $quantity = $item->getAttribute('quantity');

                    if (in_array($quantity, self::QUANTITIES, true)) {
                        $forms[$quantity] = self::decode($item->textContent);
                    }
                }

                $entries[$name] = $forms;
            }
        }

        return $entries;
    }

    /**
     * @param  array<string, string|array<string, string>>  $entries  in output order
     */
    public static function build(array $entries, string $locale): string
    {
        $lines = [
            '<?xml version="1.0" encoding="utf-8"?>',
            '<!-- Generated by Dorr translation management ('.self::attribute($locale).'). Re-export from the dashboard instead of editing by hand. -->',
            '<resources>',
        ];

        foreach ($entries as $name => $value) {
            $attribute = self::attribute((string) $name);

            if (is_array($value)) {
                $lines[] = '    <plurals name="'.$attribute.'">';

                foreach (self::QUANTITIES as $quantity) {
                    if (isset($value[$quantity]) && $value[$quantity] !== '') {
                        $lines[] = '        <item quantity="'.$quantity.'">'.self::encode($value[$quantity]).'</item>';
                    }
                }

                $lines[] = '    </plurals>';

                continue;
            }

            $lines[] = '    <string name="'.$attribute.'">'.self::encode($value).'</string>';
        }

        $lines[] = '</resources>';

        return implode("\n", $lines)."\n";
    }

    /**
     * Android resource text → plain text (\' \" \n \t \\ \@ \? \uXXXX, surrounding quotes).
     */
    public static function decode(string $raw): string
    {
        if (strlen($raw) >= 2 && str_starts_with($raw, '"') && str_ends_with($raw, '"')) {
            $raw = substr($raw, 1, -1);
        }

        return (string) preg_replace_callback('/\\\\(u[0-9a-fA-F]{4}|.)/su', static function (array $match): string {
            $token = $match[1];

            if (strlen($token) === 5 && $token[0] === 'u') {
                return mb_chr((int) hexdec(substr($token, 1)), 'UTF-8');
            }

            return match ($token) {
                'n' => "\n",
                't' => "\t",
                default => $token,
            };
        }, $raw);
    }

    /**
     * Plain text → Android resource text, XML-escaped.
     */
    public static function encode(string $text): string
    {
        $escaped = str_replace(
            ['\\', "\n", "\t", "'", '"'],
            ['\\\\', '\\n', '\\t', "\\'", '\\"'],
            $text,
        );

        if (str_starts_with($escaped, '@') || str_starts_with($escaped, '?')) {
            $escaped = '\\'.$escaped;
        }

        return htmlspecialchars($escaped, ENT_XML1 | ENT_NOQUOTES, 'UTF-8');
    }

    /**
     * Resource directory for a language code: fr → values-fr, pt-br → values-pt-rBR, zh-hans → values-b+zh+Hans.
     */
    public static function qualifier(string $locale): string
    {
        $parts = preg_split('/[-_]/', strtolower(trim($locale))) ?: [];
        $language = $parts[0] ?? '';
        $language = ['he' => 'iw', 'id' => 'in', 'yi' => 'ji'][$language] ?? $language;
        $subtags = array_slice($parts, 1);

        if ($subtags === []) {
            return 'values-'.$language;
        }

        if (count($subtags) === 1 && preg_match('/^([a-z]{2}|\d{3})$/', $subtags[0])) {
            return 'values-'.$language.'-r'.strtoupper($subtags[0]);
        }

        $formatted = array_map(static fn (string $tag): string => match (strlen($tag)) {
            2 => strtoupper($tag),
            4 => ucfirst($tag),
            default => $tag,
        }, $subtags);

        return 'values-b+'.implode('+', [$language, ...$formatted]);
    }

    /**
     * CLDR plural categories a translator should fill for a language.
     *
     * @return list<string>
     */
    public static function pluralCategories(string $locale): array
    {
        $language = strtolower((string) (preg_split('/[-_]/', $locale)[0] ?? $locale));

        return match (true) {
            $language === 'ar' => ['zero', 'one', 'two', 'few', 'many', 'other'],
            in_array($language, ['fr', 'es', 'it', 'pt', 'ca'], true) => ['one', 'many', 'other'],
            in_array($language, ['ru', 'uk', 'be', 'pl', 'cs', 'sk', 'lt'], true) => ['one', 'few', 'many', 'other'],
            $language === 'he' => ['one', 'two', 'other'],
            in_array($language, ['ja', 'zh', 'ko', 'th', 'vi', 'id', 'ms'], true) => ['other'],
            default => ['one', 'other'],
        };
    }

    private static function attribute(string $value): string
    {
        return htmlspecialchars($value, ENT_XML1 | ENT_QUOTES, 'UTF-8');
    }
}
