import AuthLayout from '../../layouts/AuthLayout.vue';
import { resolvePage } from '../../dashboard/resolvePage';
import { resolveShell } from '../../dashboard/resolveShell';
import guest from '../../router/middleware/guest';
import auth from '../../router/middleware/auth';
const page = (viewPath) => resolvePage('admin', viewPath);

export default [
    {
        path: '/',
        component: AuthLayout,
        children: [
            {
                path: '',
                redirect: { name: 'admin.login' },
            },
            {
                path: 'login',
                name: 'admin.login',
                component: page('Login'),
                meta: { middleware: [guest] },
            },
            {
                path: 'errors/404',
                name: 'Page404',
                component: page('errors/404'),
            },
        ],
    },
    {
        path: '/',
        component: resolveShell('admin'),
        children: [
            {
                path: 'dashboard',
                name: 'admin.dashboard',
                component: page('Dashboard'),
                meta: { middleware: [auth] },
            },
            {
                path: 'flags',
                name: 'admin.flags.index',
                component: page('flag/index'),
                meta: { middleware: [auth], permission: 'flags.view' },
            },
            {
                path: 'countries',
                name: 'admin.countries.index',
                component: page('country/index'),
                meta: { middleware: [auth], permission: 'countries.view' },
            },
            {
                path: 'currencies',
                name: 'admin.currencies.index',
                component: page('currency/index'),
                meta: { middleware: [auth], permission: 'currencies.view' },
            },
            {
                path: 'languages',
                name: 'admin.languages.index',
                component: page('language/index'),
                meta: { middleware: [auth], permission: 'languages.view' },
            },
            {
                path: 'profile',
                name: 'admin.profile',
                component: page('profile/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'dashboard-themes',
                name: 'admin.dashboard-themes.index',
                component: page('dashboard-theme/index'),
                meta: { middleware: [auth], permission: 'dashboard_themes.view' },
            },
            {
                path: 'platform-settings',
                name: 'admin.platform-settings',
                component: page('platform-settings/index'),
                meta: { middleware: [auth], permission: 'platform_settings.view' },
            },
            {
                path: 'mobile-app-fonts',
                name: 'admin.mobile-app-fonts.index',
                component: page('mobile-app-font/index'),
                meta: { middleware: [auth], permission: 'mobile_app_fonts.view' },
            },
            {
                path: 'mobile-app-colors',
                name: 'admin.mobile-app-colors',
                component: page('mobile-app-colors/index'),
                meta: { middleware: [auth], permission: 'mobile_app_color_defaults.view' },
            },
            {
                path: 'ai-settings',
                name: 'admin.ai-settings',
                component: page('ai-settings/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-plans',
                name: 'admin.ai-plans.index',
                component: page('ai-plans/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-subscriptions',
                name: 'admin.ai-subscriptions.index',
                component: page('ai-subscriptions/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-usage-sessions',
                name: 'admin.ai-usage-sessions.index',
                component: page('ai-usage-sessions/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-trial-control',
                name: 'admin.ai-trial-control.index',
                component: page('ai-trial-control/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-intents',
                name: 'admin.ai-intents.index',
                component: page('ai-intents/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-routing-policies',
                name: 'admin.ai-routing-policies.index',
                component: page('ai-routing-policies/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-gateways',
                name: 'admin.ai-gateways.index',
                component: page('ai-gateways/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-routing-rules',
                name: 'admin.ai-routing-rules.index',
                component: page('ai-routing-rules/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-safety-policies',
                name: 'admin.ai-safety-policies.index',
                component: page('ai-safety-policies/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-safety-rules',
                name: 'admin.ai-safety-rules.index',
                component: page('ai-safety-rules/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-safety-events',
                name: 'admin.ai-safety-events.index',
                component: page('ai-safety-events/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-safety-scans',
                name: 'admin.ai-safety-scans.index',
                component: page('ai-safety-scans/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-security-policies',
                name: 'admin.ai-security-policies.index',
                component: page('ai-security-policies/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-data-policies',
                name: 'admin.ai-data-policies.index',
                component: page('ai-data-policies/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-provider-data-rules',
                name: 'admin.ai-provider-data-rules.index',
                component: page('ai-provider-data-rules/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-security-events',
                name: 'admin.ai-security-events.index',
                component: page('ai-security-events/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-requests',
                name: 'admin.ai-requests.index',
                component: page('ai-requests/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-responses',
                name: 'admin.ai-responses.index',
                component: page('ai-responses/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-usage',
                name: 'admin.ai-usage.index',
                component: page('ai-usage/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-conversation-contexts',
                name: 'admin.ai-conversation-contexts.index',
                component: page('ai-conversation-contexts/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-conversation-attachments',
                name: 'admin.ai-conversation-attachments.index',
                component: page('ai-conversation-attachments/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-conversation-instructions',
                name: 'admin.ai-conversation-instructions.index',
                component: page('ai-conversation-instructions/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-provider-logs',
                name: 'admin.ai-provider-logs.index',
                component: page('ai-provider-logs/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-audit-events',
                name: 'admin.ai-audit-events.index',
                component: page('ai-audit-events/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-provider-health',
                name: 'admin.ai-provider-health.index',
                component: page('ai-provider-health/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-failovers',
                name: 'admin.ai-failovers.index',
                component: page('ai-failovers/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-verifications',
                name: 'admin.ai-verifications.index',
                component: page('ai-verifications/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-feature-flags',
                name: 'admin.ai-feature-flags.index',
                component: page('ai-feature-flags/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-domain-policies',
                name: 'admin.ai-domain-policies.index',
                component: page('ai-domain-policies/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-code-executions',
                name: 'admin.ai-code-executions.index',
                component: page('ai-code-executions/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-benchmark-cases',
                name: 'admin.ai-benchmark-cases.index',
                component: page('ai-benchmark-cases/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-benchmark-runs',
                name: 'admin.ai-benchmark-runs.index',
                component: page('ai-benchmark-runs/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-reliability-metrics',
                name: 'admin.ai-reliability-metrics.index',
                component: page('ai-reliability-metrics/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-languages',
                name: 'admin.ai-languages.index',
                component: page('ai-languages/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-locales',
                name: 'admin.ai-locales.index',
                component: page('ai-locales/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-language-variants',
                name: 'admin.ai-language-variants.index',
                component: page('ai-language-variants/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-user-language-preferences',
                name: 'admin.ai-user-language-preferences.index',
                component: page('ai-user-language-preferences/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-language-evaluations',
                name: 'admin.ai-language-evaluations.index',
                component: page('ai-language-evaluations/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-files',
                name: 'admin.ai-files.index',
                component: page('ai-files/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-file-processing',
                name: 'admin.ai-file-processing.index',
                component: page('ai-file-processing/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-knowledge-sources',
                name: 'admin.ai-knowledge-sources.index',
                component: page('ai-knowledge-sources/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-knowledge-chunks',
                name: 'admin.ai-knowledge-chunks.index',
                component: page('ai-knowledge-chunks/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-document-generations',
                name: 'admin.ai-document-generations.index',
                component: page('ai-document-generations/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-project-instructions',
                name: 'admin.ai-project-instructions.index',
                component: page('ai-project-instructions/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'ai-project-context',
                name: 'admin.ai-project-context.index',
                component: page('ai-project-context/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'users',
                name: 'admin.users.index',
                component: page('user/index'),
                meta: { middleware: [auth], permission: 'users.view' },
            },
            {
                path: 'employees',
                name: 'admin.employees.index',
                component: page('employee/index'),
                meta: { middleware: [auth], permission: 'admins.view' },
            },
            {
                path: 'roles',
                name: 'admin.roles.index',
                component: page('role/index'),
                meta: { middleware: [auth], permission: 'roles.view' },
            },
            {
                path: 'service-categories',
                name: 'admin.service-categories.index',
                component: page('service-category/index'),
                meta: { middleware: [auth], permission: 'service_categories.view' },
            },
            {
                // No permission: every admin has their own notifications.
                path: 'notifications',
                name: 'admin.notifications.index',
                component: page('notifications/index'),
                meta: { middleware: [auth] },
            },
            {
                path: 'wallet/wallets',
                name: 'admin.wallet.wallets',
                component: page('wallet/wallets/index'),
                meta: { middleware: [auth], permission: 'wallets.view' },
            },
            {
                path: 'wallet/online-transactions',
                name: 'admin.wallet.online-transactions',
                component: page('wallet/online-transactions/index'),
                meta: { middleware: [auth], permission: 'online-transactions.view' },
            },
            {
                path: 'wallet/withdrawals',
                name: 'admin.wallet.withdrawals',
                component: page('wallet/withdrawals/index'),
                meta: { middleware: [auth], permission: 'withdrawal-requests.view' },
            },
            {
                path: 'wallet/pin-recovery',
                name: 'admin.wallet.pin-recovery',
                component: page('wallet/pin-recovery/index'),
                meta: { middleware: [auth], permission: 'pin-recovery-requests.view' },
            },
            {
                path: 'wallet/financial-entries',
                name: 'admin.wallet.financial-entries',
                component: page('wallet/financial-entries/index'),
                meta: { middleware: [auth], permission: 'financial-entries.view' },
            },
            {
                path: 'wallet/payment-methods',
                name: 'admin.wallet.payment-methods',
                component: page('wallet/payment-methods/index'),
                meta: { middleware: [auth], permission: 'payment-methods.view' },
            },
            {
                path: 'wallet/fee-rules',
                name: 'admin.wallet.fee-rules',
                component: page('wallet/fee-rules/index'),
                meta: { middleware: [auth], permission: 'wallet-fee-rules.view' },
            },
            {
                path: 'wallet/settings',
                name: 'admin.wallet.settings',
                component: page('wallet/settings/index'),
                meta: { middleware: [auth], permission: 'wallet-settings.view' },
            },
            {
                path: 'chat/settings',
                name: 'admin.chat.settings',
                component: page('chat/settings/index'),
                meta: { middleware: [auth], permission: 'chat-settings.view' },
            },
            {
                path: 'chat/themes',
                name: 'admin.chat.themes',
                component: page('chat/themes/index'),
                meta: { middleware: [auth], permission: 'chat-themes.view' },
            },
            {
                path: 'chat/report-types',
                name: 'admin.chat.report-types',
                component: page('chat/report-types/index'),
                meta: { middleware: [auth], permission: 'chat-report-types.view' },
            },
            {
                path: 'chat/reports',
                name: 'admin.chat.reports',
                component: page('chat/reports/index'),
                meta: { middleware: [auth], permission: 'chat-reports.view' },
            },
            {
                path: 'providers',
                name: 'admin.providers.index',
                component: page('provider/index'),
                meta: { middleware: [auth] },
            },
        ],
    },
];
