<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('chat_messages', function (Blueprint $table) {
            $table->id();
            // Generated by the app when it can (optimistic sending): the same uuid sent twice is the same message.
            $table->uuid('uuid')->unique();
            $table->foreignId('conversation_id')->constrained('chat_conversations')->cascadeOnDelete();
            $table->string('sender_type', 32)->nullable()->comment('null = system message');
            $table->unsignedBigInteger('sender_id')->nullable();
            $table->string('type', 24);
            $table->text('body')->nullable();
            $table->json('meta')->nullable()->comment('location, contact card, voice waveform, wallet receipt, call, system event');
            $table->foreignId('reply_to_id')->nullable()->constrained('chat_messages')->nullOnDelete();
            $table->boolean('is_forwarded')->default(false);
            $table->unsignedInteger('forward_score')->default(0)->comment('times forwarded along a chain');
            $table->json('mentions')->nullable();
            $table->boolean('has_link')->default(false);
            $table->timestamp('edited_at')->nullable();
            $table->timestamp('deleted_for_everyone_at')->nullable();
            $table->timestamp('expires_at')->nullable()->index()->comment('disappearing messages');
            $table->timestamps();

            $table->index(['conversation_id', 'id']);
            $table->index(['sender_type', 'sender_id']);
        });

        // Group messages only: who received / read each message and when ("Message info").
        // A direct chat needs no per-message rows: the other side's last_read_message_id says it all.
        Schema::create('chat_message_receipts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('message_id')->constrained('chat_messages')->cascadeOnDelete();
            $table->foreignId('participant_id')->constrained('chat_participants')->cascadeOnDelete();
            $table->timestamp('delivered_at')->nullable();
            $table->timestamp('read_at')->nullable();

            $table->unique(['message_id', 'participant_id']);
        });

        Schema::create('chat_message_reactions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('message_id')->constrained('chat_messages')->cascadeOnDelete();
            $table->foreignId('participant_id')->constrained('chat_participants')->cascadeOnDelete();
            $table->string('emoji', 32);
            $table->timestamps();

            $table->unique(['message_id', 'participant_id']);
        });

        // One person's own marks on a message: starred, or deleted "for me".
        Schema::create('chat_message_user_states', function (Blueprint $table) {
            $table->id();
            $table->foreignId('message_id')->constrained('chat_messages')->cascadeOnDelete();
            $table->foreignId('participant_id')->constrained('chat_participants')->cascadeOnDelete();
            $table->timestamp('starred_at')->nullable();
            $table->timestamp('deleted_at')->nullable();

            $table->unique(['message_id', 'participant_id']);
        });

        Schema::create('chat_pinned_messages', function (Blueprint $table) {
            $table->id();
            $table->foreignId('conversation_id')->constrained('chat_conversations')->cascadeOnDelete();
            $table->foreignId('message_id')->constrained('chat_messages')->cascadeOnDelete();
            $table->foreignId('pinned_by_participant_id')->constrained('chat_participants')->cascadeOnDelete();
            $table->timestamp('expires_at')->nullable();
            $table->timestamps();

            $table->unique(['conversation_id', 'message_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('chat_pinned_messages');
        Schema::dropIfExists('chat_message_user_states');
        Schema::dropIfExists('chat_message_reactions');
        Schema::dropIfExists('chat_message_receipts');
        Schema::dropIfExists('chat_messages');
    }
};
